name: MSI Gapup Alert

on:
  schedule:
    - cron: '47 3 * * 1-5'
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install pandas requests

      - name: Run alert
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python gapup_alert.py
